"""
Calibrate the morphology priors for ViDEC-Inspect v0.2 from binary masks.

Consumes:
- a directory of crack binary masks (PNG, foreground > 0),
- a directory of spall binary masks (PNG),
- a pixel_to_meter scale.

Writes calibrated crack_model.calibrated.yaml and spall_model.calibrated.yaml,
plus a provenance JSON with the empirical distributions.

Usage on the in-house v0.1 masks (a real calibration corpus generated by the
v0.1 procedural pipeline; treats v0.1 masks as a stand-in until a public
real mask dataset is available):

    python scripts/calibrate_morphology.py \\
        --crack_masks_dir data/raw/v01_full \\
        --crack_glob 'crack_*.png' \\
        --spall_masks_dir data/raw/v01_full \\
        --spall_glob 'spall_*.png' \\
        --pixel_to_meter 0.00156 \\
        --output_crack_yaml configs/morphology/crack_model.calibrated.yaml \\
        --output_spall_yaml configs/morphology/spall_model.calibrated.yaml \\
        --provenance_json reports/calibration/morphology_provenance.json \\
        --source_description "v0.1 procedural mask corpus (100 crack + 100 spall)"
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import yaml

from src.calibration.morphology_calibration import (
    fit_crack_morphology,
    fit_spall_morphology,
)
from src.calibration.yaml_writer import (
    write_calibrated_crack_yaml,
    write_calibrated_spall_yaml,
)


def _collect(masks_dir: Path, glob_pattern: str):
    if not masks_dir.exists():
        return []
    return sorted(masks_dir.rglob(glob_pattern))


def _load_fallback(path: Path) -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--crack_masks_dir", required=False)
    ap.add_argument("--crack_glob", default="crack_*.png")
    ap.add_argument("--spall_masks_dir", required=False)
    ap.add_argument("--spall_glob", default="spall_*.png")
    ap.add_argument("--pixel_to_meter", type=float, required=True,
                    help="Pixel-to-meter scale used to convert mask px to m.")
    ap.add_argument("--output_crack_yaml",
                    default="configs/morphology/crack_model.calibrated.yaml")
    ap.add_argument("--output_spall_yaml",
                    default="configs/morphology/spall_model.calibrated.yaml")
    ap.add_argument("--fallback_crack_yaml",
                    default="configs/morphology/crack_model.yaml")
    ap.add_argument("--fallback_spall_yaml",
                    default="configs/morphology/spall_model.yaml")
    ap.add_argument("--provenance_json",
                    default="reports/calibration/morphology_provenance.json")
    ap.add_argument("--source_description", type=str,
                    default="Unspecified crack/spall mask corpus")
    args = ap.parse_args()

    crack_paths = []
    if args.crack_masks_dir:
        crack_paths = _collect(Path(args.crack_masks_dir), args.crack_glob)
        print(f"crack masks found: {len(crack_paths)}")

    spall_paths = []
    if args.spall_masks_dir:
        spall_paths = _collect(Path(args.spall_masks_dir), args.spall_glob)
        print(f"spall masks found: {len(spall_paths)}")

    fb_crack = _load_fallback(Path(args.fallback_crack_yaml))
    fb_spall = _load_fallback(Path(args.fallback_spall_yaml))

    crack_fit = fit_crack_morphology(crack_paths, args.pixel_to_meter) if crack_paths else {"num_samples": 0}
    spall_fit = fit_spall_morphology(spall_paths, args.pixel_to_meter) if spall_paths else {"num_samples": 0}

    write_calibrated_crack_yaml(
        fit=crack_fit,
        output_path=args.output_crack_yaml,
        source_description=args.source_description,
        fallback_v02=fb_crack,
    )
    write_calibrated_spall_yaml(
        fit=spall_fit,
        output_path=args.output_spall_yaml,
        source_description=args.source_description,
        fallback_v02=fb_spall,
    )

    prov_path = Path(args.provenance_json)
    prov_path.parent.mkdir(parents=True, exist_ok=True)
    with open(prov_path, "w") as f:
        json.dump({"crack_fit": crack_fit, "spall_fit": spall_fit}, f, indent=2, default=float)

    print(f"\nWrote calibrated crack YAML to: {args.output_crack_yaml}")
    print(f"Wrote calibrated spall YAML to: {args.output_spall_yaml}")
    print(f"Wrote morphology provenance JSON to: {args.provenance_json}")

    if crack_fit.get("num_samples"):
        ld = crack_fit.get("length_distribution") or {}
        wd = crack_fit.get("width_distribution") or {}
        print(f"  crack: n={crack_fit['num_samples']}  "
              f"length: median={ld.get('median'):.3f}m  "
              f"width: median={wd.get('median'):.3f}mm")
    if spall_fit.get("num_samples"):
        ad = spall_fit.get("area_distribution") or {}
        print(f"  spall: n={spall_fit['num_samples']}  "
              f"area: median={ad.get('median'):.6f}m^2")


if __name__ == "__main__":
    main()
